### ISSUE TITLE
Proposed standardization of the data frame

### ISSUE THREAD

**Issue by iambaim** [CRIMAC-WP4-Machine-learning/CRIMAC-annotationtools#2]
I would like to propose new names and types for the annotations in the data frame format:
```python
{
    'ping_time': 'datetime64[ns]',
    'mask_depth_upper': 'float64',
    'mask_depth_lower': 'float64',
    'priority': 'int64',
    'acoustic_category': 'string',
    'proportion': 'float64',
    'object_id': 'string',
    'channel_id': 'string'
}
```
The above based on the suggestions from @ingeke and myself . What do you think @sindrevatnehol, @albao11 and @ingridut? I plan to propose this to the bigger ICES forum afterward.

Thanks!

**Comment by sindrevatnehol** [comment]
Hi. I just had a quick look at https://github.com/ices-publications/SONAR-netCDF4/tree/master/docs 

the name "ping_time" is consistent with the netcdf time name. 

I think this can be posted to the ICES community. There is a posibility to use "backscatter_category" or "Sa_category" instead of "acoustic_category", and also "frequency_id" insted of "channel_id". But such discussion fit better in ICES.

**Comment by ingridut** [comment]
At NR, we already need to change the annotation format from a dataframe to a matrix in order to the training. The original names and data types do not really matter as long as we can easily identify what each name represent. 

I agree with Sindre that "frequency_id" may be a better choice than "channel_id".
